name: Update Filter Lists

on:
  schedule:
    - cron: "0 3 * * 1"
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_ENV: production

jobs:
  cgps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "mrrfv/cloudflare-gateway-pihole-scripts"
          ref: "v1"

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - name: Install npm dependencies
        run: npm ci

      - name: Download allowlists
        run: npm run download:allowlist
        env:
          ALLOWLIST_URLS: ${{ vars.ALLOWLIST_URLS }}

      - name: Download blocklists
        run: npm run download:blocklist
        env:
          BLOCKLIST_URLS: ${{ vars.BLOCKLIST_URLS }}

      - name: Delete old rules and lists
        run: npm run cloudflare-delete
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_LIST_ITEM_LIMIT: ${{ secrets.CLOUDFLARE_LIST_ITEM_LIMIT }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Create new rules and lists
        run: npm run cloudflare-create
        env:
          BLOCK_PAGE_ENABLED: ${{ vars.BLOCK_PAGE_ENABLED }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_LIST_ITEM_LIMIT: ${{ secrets.CLOUDFLARE_LIST_ITEM_LIMIT }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send ping request
        if: env.PING_URL != ''
        run: |
          curl "${{ env.PING_URL }}"
        env:
          PING_URL: ${{ secrets.PING_URL }}

  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Check commit
        id: check-commit
        run: |
          curl -s https://raw.githubusercontent.com/$repository/refs/heads/keepalive/date >/dev/null 2>&1
          if [ -s "commit_date" ]; then
              saved_date=$(cat commit_date)
              # Validate date format (dd/MM/YYYY)
              if [[ $saved_date =~ ^[0-9]{2}/[0-9]{2}/[0-9]{4}$ ]]; then
                  # Convert dates for comparison
                  saved_ts=$(date -d "$(echo $saved_date | sed 's/\([0-9]*\)\/\([0-9]*\)\/\([0-9]*\)/\3-\2-\1/')" +%s)
                  current_ts=$(date +%s)
                  days_diff=$(( (current_ts - saved_ts) / 86400 ))
                  if [ $days_diff -gt 30 ]; then
                      export keep_alive=1
                      date +"%d/%m/%Y" > commit_date
                  else
                      export keep_alive=0
                  fi
              else
                  # Invalid format, create new file
                  date +"%d/%m/%Y" > commit_date
                  export keep_alive=1
              fi
          else
              date +"%d/%m/%Y" > commit_date
              export keep_alive=1
          fi
      - uses: stefanzweifel/git-auto-commit-action@v5.0.0
        if: steps.check-commit.outputs.keep_alive == '1'
        with:
          branch: keepalive
          skip_checkout: true
          skip_dirty_check: true
          push_options: '--force'
          file_pattern: 'keepalive'
          commit_message: keepalive
